### ISSUE TITLE
Empty zettel.uid when there are only date in the title

### ISSUE THREAD

**Issue by pvlrmnnk** [garyng/obsidian-temple#1]
**How to reproduce**
1. Create new zettel (`202012302004.md`)
2. Use template with `{{ zettel.uid }}`
3. Get empty string

**Ecpected result**
`{{ zettel.uid }}` contains 202012302004

I don't know js/ts, but it looks like there is an issue with regex
https://github.com/garyng/obsidian-temple/blob/master/src/providers/ZettelTempleProvider.ts#L28
https://github.com/garyng/obsidian-temple/blob/master/src/providers/ZettelTempleProvider.ts#L35

Also I thinks it would be better to use `Zettel ID format` value from `Zettelkasten prefixer` config or perhaps add it to `Obsidian Temple` config

**Comment by pvlrmnnk** [comment]
I also think `zettel.date`will be useful

**Comment by garyng** [comment]
Yeah, this is probably due to the regex always requiring a `title` capture group. It should be an easy fix.

For configuring the custom format, I think it's better to let user to specify their own regex (instead of enforcing a datetime format)? Just that the regex must return the `uid` and `title` named capture group.

**Comment by garyng** [comment]
Added a new settings for overriding the extraction regex:
![image](https://user-images.githubusercontent.com/4453664/103408327-ee4df580-4b9c-11eb-9da6-2c90169dd893.png)
