### ISSUE TITLE
datetime renders as [object Object]

### ISSUE THREAD

**Issue by pvlrmnnk** [garyng/obsidian-temple#2]
**How to reproduce**
1. Add `{{ datetime }}` to emplate
2. Render it in any note, it will print [object Object]

**Ecpected result**
`{{ datetime }}` renders as `YYYY-MM-DD` by default (or any other format).

I think date format should be configurable

**Comment by pvlrmnnk** [comment]
I think we need something like https://github.com/e-picas/nunjucks-date-filter

**Comment by garyng** [comment]
It will print `[object Object]` because `datetime` is an object, you need to use [`datetime.now`](https://github.com/garyng/obsidian-temple/blob/368c54c4bd1c4489cef71ae5f02ccaca3d287553/src/providers/DateTimeContext.ts#L2) instead.

The builtin datetime provider is very dumb though.. So it might not be what you want. Contributions are welcome!

**Comment by garyng** [comment]
I looked at https://github.com/e-picas/nunjucks-date-filter before, but seems like it's unmaintained for years... I couldn't find a good alternative for now.

**Comment by pvlrmnnk** [comment]
https://www.npmjs.com/package/nunjucks-date-filter-locale seems to be what i'm looking for
it also supports timezones and locales, which is great

> So it might not be what you want. Contributions are welcome!

Ok, i'll setup proper dev env next week and try to add this filter

**Comment by garyng** [comment]
I'll take a look at this too when I have time. We probably need to allow user to configure `locale` and `timezone` in the settings page right?

**Comment by garyng** [comment]
Date formatting is now supported! See https://github.com/garyng/obsidian-temple#formatting-with-dateformat-filter
